# Generated by Django 1.9.2 on 2016-03-04 05:42
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_style', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_style_style', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
